#!/usr/bin/env python3
import csv,json,hashlib,platform,sys
from pathlib import Path
from collections import Counter
import numpy as np,cv2,torch,sklearn
from sklearn.model_selection import StratifiedGroupKFold
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parent

def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def jdump(name,obj):(ROOT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def write_csv(path,rows,fields):
 with (ROOT/path).open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n');w.writeheader();w.writerows(rows)
rows=list(csv.DictReader(open(ROOT/'01_dataset/p3_primary_manifest.csv',newline='')))
y=np.array([int(r['label_binary']) for r in rows]);groups=np.array([r['cv_group_id'] for r in rows]);X=np.zeros((len(rows),1))
chosen=None;folds=None
for n in [5,4,3]:
 sg=StratifiedGroupKFold(n_splits=n,shuffle=True,random_state=20260916);candidate=np.full(len(rows),-1)
 for fold,(_,vi) in enumerate(sg.split(X,y,groups)):candidate[vi]=fold
 ok=all(len(set(y[candidate==f]))==2 for f in range(n))
 if ok:chosen=n;folds=candidate;break
assert chosen is not None and (folds>=0).all()
out=[]
for r,f in zip(rows,folds):out.append({'media_id':r['media_id'],'label':r['label'],'group_id':r['cv_group_id'],'fold':int(f)})
write_csv('05_oof/oof_folds.csv',out,['media_id','label','group_id','fold'])
leak=sum(len({x['fold'] for x in out if x['group_id']==g})>1 for g in {x['group_id'] for x in out});assert leak==0
fold_counts={str(f):dict(Counter(x['label'] for x in out if x['fold']==f)) for f in range(chosen)}

jdump('00_protocol/relation_raster_spec.json',{'shape':[4,96,96],'dtype':'float32','crop':{'left':'x0-1.0*w','right':'x1+1.0*w','top':'y0-0.75*h','bottom':'y1+0.75*h','boundary':'clip to image'},'resize':'nearest-neighbor','channels':{'0':'target ParkScope class3 instance mask','1':'union of all ParkScope class1 and class2 masks','2':'Euclidean distance to nearest channel1 pixel; clip 24 px; divide by 24; all ones when geometry absent','3':'union of all non-target ParkScope class3 masks'},'augmentation':False,'forbidden_features':['elongation','thickness ratio','PCA','signed offset','separator score','bracket score','area support','outside fallback','ground proxy'],'sealed_evaluation_rasters_generated':False})
jdump('00_protocol/model_architecture.json',{'name':'TINY_MIL_CNN_V1','input':'4x96x96','layers':[{'type':'Conv2d','in_channels':4,'out_channels':8,'kernel_size':5,'stride':2,'padding':2},{'type':'ReLU'},{'type':'Conv2d','in_channels':8,'out_channels':16,'kernel_size':3,'stride':2,'padding':1},{'type':'ReLU'},{'type':'Conv2d','in_channels':16,'out_channels':16,'kernel_size':3,'stride':2,'padding':1},{'type':'ReLU'},{'type':'AdaptiveAvgPool2d','output_size':[1,1]},{'type':'Flatten'},{'type':'Linear','in_features':16,'out_features':1}],'frame_aggregation':'max(target_logits)','parameter_count':4313,'batch_norm':False,'dropout':False,'attention':False,'residual':False,'pretrained_backbone':False})
jdump('00_protocol/training_config.json',{'optimizer':'Adam','learning_rate':.001,'weight_decay':.0001,'epochs':100,'batch_unit':'frame','frame_batch_size':8,'loss':'BCEWithLogitsLoss','pos_weight':'training-fold negative scorable frame count / positive scorable frame count','global_seed':20260916,'fold_seed':'20260916 + fold_id','device':'cpu','augmentation':False,'early_stopping':False,'selected_epoch':100,'deterministic_algorithms':True,'unscorable_training':'skip loss','unscorable_validation':'retain; positive=>FN, negative=>non-FP'})
jdump('00_protocol/oof_protocol.json',{'method':'StratifiedGroupKFold','n_splits':chosen,'fallback_order':[5,4,3],'shuffle':True,'random_state':20260916,'group_priority':['generation_group','scenario_group','source_group','batch_group','media_id'],'selected_group_field':'media_id','selected_group_reason':'No valid non-label per-image frozen group exists; generation_group is event subtype/group_key and forbidden, capture batch is constant. Authorized media_id fallback used.','group_leakage_count':leak,'fold_class_counts':fold_counts,'sealed_eval_overlap':0,'one_oof_prediction_per_primary_frame':True})
jdump('00_protocol/threshold_protocol.json',{'grid':[round(i/100,2) for i in range(5,100,5)],'grid_count':19,'positive_rule':'probability >= threshold','unscorable_rule':'retain UNSCORABLE; positive GT counts FN, negative GT is non-FP','safe_filter':{'precision_min':.85,'fpr_max':.10},'winner_order':['recall highest','f1 highest','precision highest','threshold higher'],'hard_gate':{'precision_min':.85,'recall_min':.70,'f1_min':.75,'fpr_max':.10,'p01_recall_min':.60,'p03_recall_min':.60,'minor_crossing_fpr_max':.10,'frame_coverage_min':.95},'auc':'diagnostic only','bootstrap':{'seed':20260916,'replicates':2000,'unit':'frame','diagnostic_only':True}})
jdump('00_protocol/eval_seal.json',{'sealed_evaluation_count':30,'used_for_training':False,'used_for_oof':False,'parkscope_inference_executed':False,'rasters_generated':False,'predictions_generated':False,'gt_read_for_model_selection':False,'access_policy':'Only partition==EVALUATION media_id values read from frozen split to create exclusion set; sealed prediction JSON records skipped before JSON decoding.'})
protocol='''# PARKSCOPE_LEARNED_RELATION_HEAD_P3_OOF Protocol\n\nFrozen on 2026-09-16 before supervised training.\n\n## Purpose\n\nTest whether frozen ParkScope segmentation masks contain a learnable frame-level parking-relation signal using one preregistered tiny MIL CNN. This is development OOF feasibility, not parking production validation.\n\n## Data and seal\n\n- Frozen v2.2 DEV GT SHA256: `413d0226b0eb8c13f388f3adb051844b0fe6d30b1b06ebc833b614beaffd1e56`.\n- Frozen CAL/EVAL split SHA256: `bf8d5ba02dc0a2c5a0f1384ca0dfacd9afe3dcdbd440c7775b9cdd943d68b332`.\n- 30 sealed EVALUATION media IDs are exclusion-only. Their GT, subgroup, images, ParkScope outputs, rasters, and predictions are not used.\n- Exclude 24 uncertain and 18 gate-secondary frames. Primary pool is 166 frames: 47 positive and 119 negative.\n- Supervision is frame-level only. No target-level pseudo-labels are created.\n\n## Frozen perception and raster\n\n- ParkScope upstream commit `fbcfac7be597dd263570bbcd0377096c8a43d146`.\n- Checkpoint SHA256 `6d70bf088b7c324401afb97e09cf898afcc639d8ac837f4da7ef4afbc38d3d9b`.\n- P0 prediction records are reused only for nonsealed primary media; remaining primary media use the exact default P0 CPU call.\n- Target selection is reused exactly from matching v2.2 R0/R1 historical bbox artifacts.\n- Relation raster is fixed float32 `4x96x96`; details are in `relation_raster_spec.json`.\n\n## OOF model\n\n- `TINY_MIL_CNN_V1`, 4,313 parameters.\n- Frame logit is max over valid target logits.\n- 5-fold StratifiedGroupKFold with authorized `media_id` fallback, seed 20260916.\n- Adam, lr 0.001, weight decay 0.0001, 100 epochs, frame batch 8, fold-local pos_weight, CPU deterministic training.\n- No augmentation, early stopping, architecture search, seed sweep, handcrafted P1 features, RGB, Ollama, or VLM.\n\n## Threshold and stop rules\n\nAll OOF scores must be frozen before selection on the fixed 19-point grid 0.05..0.95. Safe thresholds require Precision >=0.85 and FPR <=0.10. The winner and OOF gate are selected exactly as specified in `threshold_protocol.json`. No sealed EVALUATION is opened in this phase, including after PASS.\n'''
(ROOT/'00_protocol/P3_OOF_PROTOCOL.md').write_text(protocol)
# Pre-registration hashes cover every required pretraining artifact; preregistration itself is not self-hashed.
required=['00_protocol/P3_OOF_PROTOCOL.md','00_protocol/relation_raster_spec.json','00_protocol/model_architecture.json','00_protocol/training_config.json','00_protocol/oof_protocol.json','00_protocol/threshold_protocol.json','00_protocol/eval_seal.json','01_dataset/p3_primary_manifest.csv','03_target_binding/frozen_target_manifest.csv','04_relation_rasters/raster_manifest.csv','04_relation_rasters/raster_determinism.json','05_oof/oof_folds.csv']
pre={'frozen_at_date':'2026-09-16','training_started':False,'ollama_requests':0,'sealed_evaluation_accessed':False,'artifacts':{p:sha(ROOT/p) for p in required},'environment':{'python_version':platform.python_version(),'torch_version':torch.__version__,'sklearn_version':sklearn.__version__,'numpy_version':np.__version__,'opencv_version':cv2.__version__,'device':'cpu'},'target_manifest_sha256':sha(ROOT/'03_target_binding/frozen_target_manifest.csv'),'oof_folds_sha256':sha(ROOT/'05_oof/oof_folds.csv')}
jdump('00_protocol/preregistration.json',pre)
print(json.dumps({'n_splits':chosen,'fold_counts':fold_counts,'group_leakage':leak,'target_manifest_sha':pre['target_manifest_sha256'],'oof_folds_sha':pre['oof_folds_sha256']},indent=2))
